;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[module/systray]
type = internal/tray
format-margin = 10pt
tray-spacing = 16pt
tray-size = 21pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-underline= ${colors.secondary}
label-active-padding = 1
label-active-foreground = ${colors.foreground}

label-occupied = %name%
label-occupied-padding = 1
label-occupied-foreground = ${colors.primary}

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%
label-foreground = ${colors.primary}
format-prefix-foreground = ${colors.alert}

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = "  "
label-volume-foreground = ${colors.primary}
format-volume-prefix-foreground = ${colors.alert}
format-volume = <label-volume>
label-volume = %percentage%%
label-muted = muted
label-muted-foreground = ${colors.disabled}

click-right = exec pavucontrol &
click-left = pulseaudio-control togmute
click-middle = pulseaudio-control --node-blacklist "alsa_output.pci-0000_01_00.1.hdmi-stereo-extra2" next-node

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "  "
label-foreground = ${colors.primary}
format-prefix-foreground = ${colors.alert}
label = %percentage:2%%

[module/date]
type = internal/date
interval = 1
date = %A, %d.%m %H:%M
label = %date%
label-foreground = ${colors.primary}

[module/rofi]
type = custom/text 
content =" "
content-padding = 1
click-left = exec rofi -show run
content-foreground =  ${colors.secondary}

[module/poweroff]
type = custom/text 
content ="   "
content-padding = 1
click-left = exec systemctl poweroff
content-foreground =  ${colors.alert}

[module/reboot]
type = custom/text 
content ="  "
content-padding = 1
click-left = exec systemctl reboot
content-foreground =  ${colors.secondary}

[module/spotify]
type = custom/script
tail = true
interval = 1
format-prefix = "   "
format = <label>
exec = ~/.config/polybar/scripts/scroll_spotify_status.sh
label-foreground = ${colors.primary}
format-prefix-foreground = ${colors.alert}
